language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.6
  - pypy
  - pypy3

notifications:
  email:
    recipients:
      - rinat.sabitov@gmail.com
    on_success: change
    on_failure: change

install:
  - unittest2 pip coverage install nose coveralls

script:
  - nosetests -vv --with-coverage --cover-erase --cover-package=descript.ion --with-doctest

after_success:
    - coveralls
